### ISSUE TITLE
tracking issue for next major version (5.0.0)

### ISSUE THREAD

**Issue by mnater** [mnater/Hyphenopoly#171]
- [x] merge i167 (succinct data structures)
- [x] document succinct data structure
- [x] drop support for node 10
- [x] rewrite Hyphenopoly.config see #170
- [x] document Hyphenopoly.config 
- [x] clean up and document tools
- [x] document usage of .wasm-files w/o Hyphenopoly
- ~~[x] change API for hiding to numbers only~~[^1]
- [x] remove necessity to clone instances
- [x] ES Module
- [x] Deno
- [x] #195
- [x] #196
- [x] Check error reporting in module
[^1]: current implementation is already enough space saving and using numbers isn't very intuitive

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenopoly/commit/b73b5164f94e05c4378a70b98333a1c9c1057b69
